server:
  port: 8030

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nep?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

# 配置mybatis -plus的扫描
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neusoft.yth.nepBackend.entity
  configuration:
    #    关闭驼峰命名
    map-underscore-to-camel-case: true

  # 配置日志

logging:
  level:
    root: error
    com.neusoft.yth.nepBackend.aqi: debug